name = "AlgebraicMetabolism"
uuid = "b66562e1-fa90-4e8b-9505-c909188fab77"
license = "MIT"
authors = ["James Fairbanks <fairbanksj@ufl.edu>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[compat]
Catlab = "0.15"
julia = "1.9"
