name = "AlgebraicMetabolism"
uuid = "fdd843e2-20df-4918-9bc7-fd2071f1d7c3"
license = "MIT"
authors = ["James Fairbanks <fairbanksj@ufl.edu>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[compat]
Catlab = "0.15"
julia = "1.9"
